server:
  port: 8080

spring:
  application:
    name: gateway-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://eureka-server:8761/eureka
