services:
  mysql-db:
    image: mysql:8.4
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recipes_db
    ports:
      - "3306:3306"
    networks:
      - microred

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - microred

  eureka-server:
    build: ./eureka-server/eureka-server
    ports:
      - "8761:8761"
    networks:
      - microred
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/eureka/apps || exit 1"]
      interval: 5s
      retries: 10

  gateway-service:
    build: ./gateway-service/gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - microred
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/recipes_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password

  search-service:
    build: ./search-service/search-service
    ports:
      - "8081:8081"
    depends_on:
        - eureka-server
        - elastic
    networks:
      - microred
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elastic:9200

  operator-service:
    build: ./operator-service/operator-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - microred
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/recipes_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password

networks:
  microred:
