services:
  mysql-db:
    image: mysql:8.4
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: recipes_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -ppassword -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks: [microred]

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks: [microred]

  eureka-server:
    build: ./eureka-server/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8761/eureka/apps >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks: [microred]

  gateway-service:
    build: ./gateway-service/gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql-db:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/recipes_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks: [microred]

  search-service:
    build: ./search-service/search-service
    container_name: search-service
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
      elastic:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_ELASTICSEARCH_URIS=http://elastic:9200
    networks: [microred]

  operator-service:
    build: ./operator-service/operator-service
    container_name: operator-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql-db:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/recipes_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks: [microred]

networks:
  microred: {}