server:
  port: 8081

spring:
  application:
    name: search-service
  elasticsearch:
    uris: http://elastic:9200

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    service-url:
     defaultZone: http://eureka-server:8761/eureka/
