server:
  port: 8082

spring:
  application:
    name: operator-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
